
export const convenienceRecipes = [
    {
        id: 'retort-meat-doria',
        name: 'レトルトミートドリア',
        meal: 'dinner', servings: 2, difficulty: 'easy', season: ['spring', 'summer', 'autumn', 'winter'],
        calories: '約650kcal', activeTime: '10分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: 'レトルトミートソースとホワイトソースで作る超時短ドリア。',
        ingredients: ['ご飯 (パックでも可)', 'レトルトミートソース', 'レトルトホワイトソース', 'ピザ用チーズ', 'バター'],
        requiredGear: ['スキレット', 'バーナー'], usedGearIds: ['skillet'], usedHeatSourceIds: ['single-burner'],
        steps: ['スキレットにバターを塗り、ご飯を敷き詰める。', '温めたミートソースとホワイトソースをかける。', 'チーズをたっぷり乗せ、蓋をして弱火で5分。'],
        cookTime: '約15分', tips: 'パン粉を振ってから焼くとサクサク食感に。'
    },
    {
        id: 'retort-white-gratin',
        name: 'ホワイトソースグラタン',
        meal: 'dinner', servings: 2, difficulty: 'easy', season: ['autumn', 'winter'],
        calories: '約550kcal', activeTime: '10分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: 'レトルトのホワイトソースで作るお手軽グラタン。',
        ingredients: ['マカロニ (早茹で)', 'レトルトホワイトソース', 'ベーコン', 'ブロッコリー（冷凍）', 'ピザ用チーズ'],
        requiredGear: ['スキレット', '鍋'], usedGearIds: ['skillet', 'titanium-pot'], usedHeatSourceIds: ['twin-burner'],
        steps: ['マカロニを茹でる（塩水で）。', 'スキレットでベーコンを炒め、茹でたマカロニ・ブロッコリーを和える。', 'ホワイトソースをかけ、チーズを乗せて焼く。'],
        cookTime: '約20分', tips: '早茹でマカロニなら3分で茹で上がります。'
    },
    {
        id: 'frozen-pilaf-paella',
        name: '冷凍ピラフで作るパエリア',
        meal: 'dinner', servings: 2, difficulty: 'easy', season: ['summer'],
        calories: '約500kcal', activeTime: '10分', cleanupLevel: 1, prePrep: false, cost: 'mid',
        description: '冷凍エビピラフにシーフードミックスを追加するだけで本格的に。',
        ingredients: ['冷凍エビピラフ', '冷凍シーフードミックス', 'パプリカ', 'レモン', 'オリーブオイル'],
        requiredGear: ['スキレット'], usedGearIds: ['skillet'], usedHeatSourceIds: ['single-burner'],
        steps: ['オリーブオイルでシーフードミックスとパプリカを炒める。', '冷凍ピラフを加えて炒め合わせる。', 'レモンを添えて完成。'],
        cookTime: '約15分', tips: '仕上げにパセリを振ると見栄えがアップ。'
    },
    {
        id: 'retort-curry-udon',
        name: 'レトルトカレーうどん',
        meal: 'lunch', servings: 1, difficulty: 'easy', season: ['autumn', 'winter'],
        calories: '約500kcal', activeTime: '10分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: 'レトルトカレーにうどんを入れるだけのお手軽ランチ。',
        ingredients: ['レトルトカレー', 'うどん（冷凍またはチルド）', '長ねぎ', 'めんつゆ（少々）'],
        requiredGear: ['鍋'], usedGearIds: ['titanium-pot'], usedHeatSourceIds: ['single-burner'],
        steps: ['うどんを茹でる。', 'レトルトカレーを温め、めんつゆで少し伸ばす。', 'うどんにかけてネギを乗せる。'],
        cookTime: '約10分', tips: '揚げ玉を乗せるとカロリーと美味しさがアップ。'
    },
    {
        id: 'frozen-gyoza-nabe',
        name: '冷凍餃子鍋',
        meal: 'dinner', servings: 2, difficulty: 'easy', season: ['winter'],
        calories: '約400kcal', activeTime: '5分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: '冷凍餃子を鍋に投入するだけの最強時短メニュー。',
        ingredients: ['冷凍餃子', '白菜（カット野菜でも可）', 'にら', '鍋つゆ（市販）'],
        requiredGear: ['鍋'], usedGearIds: ['titanium-pot'], usedHeatSourceIds: ['single-burner'],
        steps: ['鍋つゆを沸かす。', '白菜と冷凍餃子を入れて煮る。', 'にらを加えて完成。'],
        cookTime: '約15分', tips: 'ラー油とポン酢でいただくと最高。〆はラーメン。'
    },
    {
        id: 'retort-hayashi-omurice',
        name: 'ハヤシオムライス',
        meal: 'lunch', servings: 2, difficulty: 'easy', season: ['spring', 'autumn'],
        calories: '約650kcal', activeTime: '15分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: 'レトルトハヤシライスをオムライスにアレンジ。',
        ingredients: ['ご飯', 'レトルトハヤシ', '卵', 'バター', 'パセリ'],
        requiredGear: ['フライパン'], usedGearIds: ['skillet'], usedHeatSourceIds: ['single-burner'],
        steps: ['ご飯をお皿に盛る。', '卵を焼いてご飯に乗せる。', '温めたハヤシソースをかける。'],
        cookTime: '約10分', tips: '卵は半熟トロトロに仕上げるのがポイント。'
    },
    {
        id: 'instant-ramen-tsukemen',
        name: 'インスタント麺でつけ麺',
        meal: 'lunch', servings: 1, difficulty: 'easy', season: ['summer'],
        calories: '約450kcal', activeTime: '10分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: '即席麺をつけ麺風にアレンジ。夏でもサッパリ食べられる。',
        ingredients: ['インスタントラーメン（醤油or味噌）', '水', '氷', '煮卵（市販）', 'チャーシュー（市販）'],
        requiredGear: ['鍋'], usedGearIds: ['titanium-pot'], usedHeatSourceIds: ['single-burner'],
        steps: ['スープを濃いめに作る（水少なめ）。', '麺を茹で、冷水で締める。', '麺をスープにつけて食べる。'],
        cookTime: '約10分', tips: 'スープにラー油を入れると辛つけ麺に。'
    },
    {
        id: 'frozen-udon-sukiyaki',
        name: '冷凍うどんすき焼き',
        meal: 'dinner', servings: 2, difficulty: 'easy', season: ['winter'],
        calories: '約600kcal', activeTime: '15分', cleanupLevel: 1, prePrep: false, cost: 'mid',
        description: '冷凍うどんをすき焼きの〆に使う贅沢メニュー。',
        ingredients: ['冷凍うどん', '牛薄切り肉', '豆腐', 'すき焼きのたれ（市販）', '卵', 'ネギ'],
        requiredGear: ['スキレット'], usedGearIds: ['skillet'], usedHeatSourceIds: ['single-burner'],
        steps: ['すき焼きを普通に作る。', '具材を食べ終わったら冷凍うどんを投入。', '溶き卵につけて食べる。'],
        cookTime: '約20分', tips: '最初からうどんを入れてもOK。'
    },
    {
        id: 'canned-yakitori-don',
        name: '焼き鳥缶で親子丼風',
        meal: 'lunch', servings: 1, difficulty: 'easy', season: ['spring', 'summer', 'autumn', 'winter'],
        calories: '約500kcal', activeTime: '10分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: '缶詰の焼き鳥を使った超簡単親子丼。',
        ingredients: ['焼き鳥缶（タレ）', '卵', '玉ねぎ（薄切り）', 'ご飯', 'めんつゆ'],
        requiredGear: ['クッカー（小）'], usedGearIds: ['sierra-cup'], usedHeatSourceIds: ['single-burner'],
        steps: ['玉ねぎをめんつゆで煮る。', '焼き鳥缶を汁ごと加えて温める。', '溶き卵を回し入れ、ご飯に乗せる。'],
        cookTime: '約10分', tips: '刻みネギと七味をかけると本格的。'
    },
    {
        id: 'frozen-takoyaki-ahijo',
        name: '冷凍たこ焼きアヒージョ',
        meal: 'snack', servings: 2, difficulty: 'easy', season: ['spring', 'summer', 'autumn', 'winter'],
        calories: '約400kcal', activeTime: '10分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: '冷凍たこ焼きをオリーブオイルで煮るだけの新感覚おつまみ。',
        ingredients: ['冷凍たこ焼き', 'オリーブオイル', 'にんにく', '唐辛子', 'パセリ'],
        requiredGear: ['スキレット'], usedGearIds: ['skillet'], usedHeatSourceIds: ['single-burner'],
        steps: ['スキレットにオリーブオイル、にんにく、唐辛子を入れて弱火。', '冷凍たこ焼きを投入し、じっくり煮る。', 'パセリを振って完成。'],
        cookTime: '約15分', tips: 'バゲットを添えてオイルをつけて食べると最高。'
    },
    {
        id: 'retort-cream-pasta',
        name: 'レトルトクリームパスタ',
        meal: 'lunch', servings: 1, difficulty: 'easy', season: ['autumn', 'winter'],
        calories: '約600kcal', activeTime: '15分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: 'レトルトソースで作る簡単クリームパスタ。',
        ingredients: ['パスタ（早茹で）', 'レトルトクリームソース', 'ベーコン', 'ブラックペッパー', 'パセリ'],
        requiredGear: ['鍋'], usedGearIds: ['titanium-pot'], usedHeatSourceIds: ['single-burner'],
        steps: ['パスタを茹でる。', 'レトルトソースを温めてパスタと和える。', 'ベーコンを焼いてトッピング。'],
        cookTime: '約15分', tips: '早茹でパスタを使えば時短に。'
    },
    {
        id: 'frozen-pizza-skillet',
        name: 'スキレット冷凍ピザ',
        meal: 'snack', servings: 2, difficulty: 'easy', season: ['spring', 'summer', 'autumn', 'winter'],
        calories: '約500kcal', activeTime: '5分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: '冷凍ピザをスキレットで焼くだけ。底がカリカリに。',
        ingredients: ['冷凍ピザ', '追加チーズ（お好みで）', 'タバスコ'],
        requiredGear: ['スキレット'], usedGearIds: ['skillet'], usedHeatSourceIds: ['single-burner'],
        steps: ['スキレットに冷凍ピザを置く。', '蓋をして弱火〜中火で焼く。', 'チーズが溶けて底がカリカリになったら完成。'],
        cookTime: '約10分', tips: 'アルミホイルで蓋をしても可。'
    },
    {
        id: 'retort-mapo-rice',
        name: 'レトルト麻婆豆腐丼',
        meal: 'dinner', servings: 2, difficulty: 'easy', season: ['autumn', 'winter'],
        calories: '約550kcal', activeTime: '10分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: 'レトルト麻婆豆腐をご飯にかけるだけ。寒い日に最高。',
        ingredients: ['ご飯', 'レトルト麻婆豆腐', '長ねぎ', 'ラー油', '花椒（あれば）'],
        requiredGear: ['鍋'], usedGearIds: ['titanium-pot'], usedHeatSourceIds: ['single-burner'],
        steps: ['レトルト麻婆豆腐を温める。', 'ご飯にかけてネギとラー油をトッピング。'],
        cookTime: '約10分', tips: '豆腐を追加すると具だくさんに。'
    },
    {
        id: 'frozen-nikuman-steam',
        name: '蒸し肉まん',
        meal: 'breakfast', servings: 2, difficulty: 'easy', season: ['autumn', 'winter'],
        calories: '約300kcal', activeTime: '5分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: '冷凍肉まんをクッカーで蒸すだけの簡単朝食。',
        ingredients: ['冷凍肉まん', '水'],
        requiredGear: ['クッカー', '蒸し器用網'], usedGearIds: ['titanium-pot'], usedHeatSourceIds: ['single-burner'],
        steps: ['クッカーに水を少量入れ、網を置く。', '冷凍肉まんを乗せて蓋をし、蒸す。'],
        cookTime: '約15分', tips: '網がなければアルミホイルを丸めて敷いても可。'
    },
    {
        id: 'canned-sardine-pasta',
        name: 'サバ缶パスタ',
        meal: 'lunch', servings: 1, difficulty: 'easy', season: ['spring', 'summer', 'autumn', 'winter'],
        calories: '約550kcal', activeTime: '15分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: 'サバ缶で作るペペロンチーノ風パスタ。栄養満点。',
        ingredients: ['パスタ', 'サバ水煮缶', 'にんにく', '唐辛子', 'オリーブオイル', '醤油'],
        requiredGear: ['鍋', 'フライパン'], usedGearIds: ['titanium-pot', 'skillet'], usedHeatSourceIds: ['twin-burner'],
        steps: ['パスタを茹でる。', 'オリーブオイルでにんにくと唐辛子を炒める。', 'サバ缶を崩しながら加え、パスタと和えて醤油で味付け。'],
        cookTime: '約15分', tips: '大葉を乗せると和風感アップ。'
    },
    // ===== 追加レシピ（20件）=====
    {
        id: 'retort-pasta-arabiata',
        name: 'レトルトアラビアータ',
        meal: 'lunch', servings: 1, difficulty: 'easy', season: ['spring', 'summer', 'autumn', 'winter'],
        calories: '約500kcal', activeTime: '10分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: 'ピリ辛トマトソースのパスタ。レトルトなのに本格的。',
        ingredients: ['パスタ', 'レトルトアラビアータソース', 'ベーコン', '粉チーズ', 'パセリ'],
        requiredGear: ['鍋'], usedGearIds: ['titanium-pot'], usedHeatSourceIds: ['single-burner'],
        steps: ['パスタを茹でる。', 'レトルトソースを温め和える。', '追加ベーコンとチーズをトッピング。'],
        cookTime: '約15分', tips: 'タバスコを足すとさらに辛く。'
    },
    {
        id: 'canned-corned-hash',
        name: 'コンビーフハッシュ',
        meal: 'breakfast', servings: 2, difficulty: 'easy', season: ['spring', 'summer', 'autumn', 'winter'],
        calories: '約450kcal', activeTime: '15分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: 'コンビーフとジャガイモを炒めたアメリカンブレックファスト。',
        ingredients: ['コンビーフ缶', 'じゃがいも（冷凍ハッシュポテトでも可）', '卵', '塩コショウ'],
        requiredGear: ['スキレット'], usedGearIds: ['skillet'], usedHeatSourceIds: ['single-burner'],
        steps: ['ジャガイモを炒める（冷凍ならそのまま投入）。', 'コンビーフを加えて崩しながら炒める。', '卵を落として半熟で完成。'],
        cookTime: '約15分', tips: 'トーストを添えると最高。'
    },
    {
        id: 'instant-soup-risotto',
        name: 'カップスープリゾット',
        meal: 'breakfast', servings: 1, difficulty: 'easy', season: ['autumn', 'winter'],
        calories: '約300kcal', activeTime: '5分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: 'カップスープにご飯を入れるだけの超簡単リゾット。',
        ingredients: ['カップスープの素（ポタージュ系）', 'ご飯（パックでも可）', 'チーズ', 'パセリ'],
        requiredGear: ['シェラカップ'], usedGearIds: ['sierra-cup'], usedHeatSourceIds: ['single-burner'],
        steps: ['スープを規定より少ないお湯で作る。', 'ご飯とチーズを入れて混ぜる。'],
        cookTime: '約5分', tips: 'コーンスープが一番合います。'
    },
    {
        id: 'frozen-okonomiyaki',
        name: '冷凍お好み焼き',
        meal: 'lunch', servings: 1, difficulty: 'easy', season: ['spring', 'summer', 'autumn', 'winter'],
        calories: '約500kcal', activeTime: '5分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: '冷凍お好み焼きをスキレットで温めるだけ。本格的な味。',
        ingredients: ['冷凍お好み焼き', 'ソース', 'マヨネーズ', '鰹節', '青のり'],
        requiredGear: ['スキレット'], usedGearIds: ['skillet'], usedHeatSourceIds: ['single-burner'],
        steps: ['スキレットに冷凍お好み焼きを乗せる。', '蓋をして中火で両面を焼く。', 'ソースとマヨネーズをかける。'],
        cookTime: '約10分', tips: '焼きそばを添えると満足度アップ。'
    },
    {
        id: 'retort-beef-stew-pasta',
        name: 'ビーフシチューパスタ',
        meal: 'dinner', servings: 2, difficulty: 'easy', season: ['autumn', 'winter'],
        calories: '約650kcal', activeTime: '15分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: 'レトルトビーフシチューをパスタソースに。濃厚で美味しい。',
        ingredients: ['パスタ', 'レトルトビーフシチュー', 'ブロッコリー（冷凍）', '粉チーズ'],
        requiredGear: ['鍋'], usedGearIds: ['titanium-pot'], usedHeatSourceIds: ['single-burner'],
        steps: ['パスタを茹でる（ブロッコリーも一緒に）。', 'ビーフシチューを温めてかける。'],
        cookTime: '約15分', tips: 'フェットチーネなど太めの麺が合う。'
    },
    {
        id: 'frozen-takikomi-gohan',
        name: '冷凍炊き込みご飯',
        meal: 'dinner', servings: 2, difficulty: 'easy', season: ['autumn', 'winter'],
        calories: '約400kcal', activeTime: '5分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: '冷凍の炊き込みご飯を温めるだけ。おかずなしでも満足。',
        ingredients: ['冷凍炊き込みご飯', '味噌汁の素'],
        requiredGear: ['スキレット'], usedGearIds: ['skillet'], usedHeatSourceIds: ['single-burner'],
        steps: ['スキレットで蓋をして蒸し焼きに温める。'],
        cookTime: '約10分', tips: '具だくさん味噌汁と一緒に。'
    },
    {
        id: 'canned-mackerel-curry',
        name: 'サバ缶カレー',
        meal: 'dinner', servings: 2, difficulty: 'easy', season: ['spring', 'summer', 'autumn', 'winter'],
        calories: '約600kcal', activeTime: '15分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: 'サバ味噌缶とカレールーで作る時短カレー。',
        ingredients: ['サバ味噌缶', 'カレールー（1かけ）', '玉ねぎ', 'ご飯', '水'],
        requiredGear: ['鍋'], usedGearIds: ['titanium-pot'], usedHeatSourceIds: ['single-burner'],
        steps: ['玉ねぎを炒める。', 'サバ缶と水を加えて煮る。', 'ルーを溶かしてご飯にかける。'],
        cookTime: '約15分', tips: '味噌味がカレーにコクを出す。'
    },
    {
        id: 'instant-yakisoba-omelette',
        name: 'カップ焼きそばオムレツ',
        meal: 'lunch', servings: 1, difficulty: 'easy', season: ['spring', 'summer', 'autumn', 'winter'],
        calories: '約500kcal', activeTime: '10分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: 'カップ焼きそばを卵で包む。B級グルメの極み。',
        ingredients: ['カップ焼きそば', '卵', 'マヨネーズ'],
        requiredGear: ['スキレット', 'お湯'], usedGearIds: ['skillet'], usedHeatSourceIds: ['single-burner'],
        steps: ['カップ焼きそばを作る。', '溶き卵を流して焼きそばを乗せて包む。'],
        cookTime: '約10分', tips: 'ソースを多めにかけると美味しい。'
    },
    {
        id: 'frozen-gratin-soup',
        name: '冷凍グラタンスープ',
        meal: 'breakfast', servings: 1, difficulty: 'easy', season: ['winter'],
        calories: '約300kcal', activeTime: '5分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: '冷凍グラタンにスープを足すだけ。フレンチオニオン風。',
        ingredients: ['冷凍グラタン（小）', 'コンソメスープ', 'フランスパン', 'チーズ'],
        requiredGear: ['スキレット', 'シェラカップ'], usedGearIds: ['skillet', 'sierra-cup'], usedHeatSourceIds: ['single-burner'],
        steps: ['グラタンを温める。', 'スープを作り、グラタンを浸すように入れる。'],
        cookTime: '約10分', tips: '寒い朝に最高。'
    },
    {
        id: 'retort-pasta-peperoncino',
        name: 'レトルトペペロンチーノ',
        meal: 'lunch', servings: 1, difficulty: 'easy', season: ['spring', 'summer', 'autumn', 'winter'],
        calories: '約450kcal', activeTime: '10分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: 'レトルトソースで作るガーリック風味のパスタ。',
        ingredients: ['パスタ', 'レトルトペペロンチーノソース', 'ベーコン', 'パセリ'],
        requiredGear: ['鍋'], usedGearIds: ['titanium-pot'], usedHeatSourceIds: ['single-burner'],
        steps: ['パスタを茹でる。', 'ソースを和える。', 'ベーコンをトッピング。'],
        cookTime: '約10分', tips: '赤唐辛子を追加すると辛さアップ。'
    },
    {
        id: 'frozen-gyoza-pan-fry',
        name: '羽根つき冷凍餃子',
        meal: 'snack', servings: 2, difficulty: 'easy', season: ['spring', 'summer', 'autumn', 'winter'],
        calories: '約350kcal', activeTime: '10分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: '冷凍餃子をスキレットでパリパリに。ビールのお供に最高。',
        ingredients: ['冷凍餃子（羽根つきタイプ）', '酢醤油', 'ラー油'],
        requiredGear: ['スキレット'], usedGearIds: ['skillet'], usedHeatSourceIds: ['single-burner'],
        steps: ['スキレットに冷凍餃子を並べる。', '水を入れて蓋をして蒸し焼き。', '水が飛んだらパリパリに焼く。'],
        cookTime: '約10分', tips: '蓋は水が残っているうちに取ると羽根がパリパリに。'
    },
    {
        id: 'canned-tomato-pasta',
        name: 'ツナトマトパスタ',
        meal: 'lunch', servings: 2, difficulty: 'easy', season: ['spring', 'summer'],
        calories: '約500kcal', activeTime: '15分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: 'ツナ缶とトマト缶で作る簡単パスタ。',
        ingredients: ['パスタ', 'ツナ缶', 'トマト缶', 'にんにく', 'オリーブオイル', '塩コショウ'],
        requiredGear: ['鍋', 'フライパン'], usedGearIds: ['titanium-pot', 'skillet'], usedHeatSourceIds: ['twin-burner'],
        steps: ['パスタを茹でる。', 'にんにくとツナを炒め、トマト缶を加えて煮詰める。', 'パスタと和える。'],
        cookTime: '約15分', tips: 'バジルを散らすと香りが良い。'
    },
    {
        id: 'frozen-hashbrown-sandwich',
        name: 'ハッシュポテトサンド',
        meal: 'breakfast', servings: 1, difficulty: 'easy', season: ['spring', 'summer', 'autumn', 'winter'],
        calories: '約400kcal', activeTime: '10分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: '冷凍ハッシュポテトをパンに挟む。ファストフード気分。',
        ingredients: ['冷凍ハッシュポテト', 'バンズ（またはマフィン）', 'ベーコン', 'チーズ', 'ケチャップ'],
        requiredGear: ['スキレット'], usedGearIds: ['skillet'], usedHeatSourceIds: ['single-burner'],
        steps: ['ハッシュポテトとベーコンを焼く。', 'バンズに挟む。'],
        cookTime: '約10分', tips: '目玉焼きを追加すると完璧。'
    },
    {
        id: 'retort-cream-stew-udon',
        name: 'クリームシチューうどん',
        meal: 'dinner', servings: 2, difficulty: 'easy', season: ['winter'],
        calories: '約500kcal', activeTime: '10分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: 'レトルトクリームシチューにうどんを入れる新感覚。',
        ingredients: ['レトルトクリームシチュー', '冷凍うどん', 'ブロッコリー（冷凍）', '粗挽きコショウ'],
        requiredGear: ['鍋'], usedGearIds: ['titanium-pot'], usedHeatSourceIds: ['single-burner'],
        steps: ['シチューを温め、うどんとブロッコリーを入れて煮る。'],
        cookTime: '約10分', tips: 'チーズを乗せるとさらに濃厚に。'
    },
    {
        id: 'instant-ochazuke-salmon',
        name: '鮭茶漬け（レトルト）',
        meal: 'breakfast', servings: 1, difficulty: 'easy', season: ['spring', 'summer', 'autumn', 'winter'],
        calories: '約300kcal', activeTime: '5分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: '鮭フレークとお茶漬けの素で作る贅沢朝食。',
        ingredients: ['ご飯', 'お茶漬けの素', '鮭フレーク', 'わさび', 'お湯'],
        requiredGear: ['シェラカップ'], usedGearIds: ['sierra-cup'], usedHeatSourceIds: ['single-burner'],
        steps: ['ご飯に鮭フレークとお茶漬けの素を乗せる。', 'お湯を注ぐ。'],
        cookTime: '約3分', tips: '焼きおにぎりに出汁茶漬けも美味しい。'
    },
    {
        id: 'frozen-fried-noodle',
        name: '冷凍焼きそば',
        meal: 'lunch', servings: 2, difficulty: 'easy', season: ['spring', 'summer', 'autumn', 'winter'],
        calories: '約500kcal', activeTime: '10分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: '冷凍焼きそばをフライパンで炒めるだけ。野菜を足せば完璧。',
        ingredients: ['冷凍焼きそば', 'キャベツ（カット野菜）', '目玉焼き用卵'],
        requiredGear: ['フライパン'], usedGearIds: ['skillet'], usedHeatSourceIds: ['single-burner'],
        steps: ['カット野菜を炒める。', '冷凍焼きそばを加えて炒める。', '目玉焼きを乗せる。'],
        cookTime: '約10分', tips: '紅生姜を忘れずに。'
    },
    {
        id: 'canned-chili-beans-rice',
        name: 'チリビーンズライス',
        meal: 'dinner', servings: 2, difficulty: 'easy', season: ['autumn', 'winter'],
        calories: '約550kcal', activeTime: '10分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: '缶詰のチリビーンズをご飯にかけるだけ。スパイシー。',
        ingredients: ['チリビーンズ缶', 'ご飯', 'チーズ', 'サワークリーム（あれば）'],
        requiredGear: ['鍋'], usedGearIds: ['titanium-pot'], usedHeatSourceIds: ['single-burner'],
        steps: ['チリビーンズを温める。', 'ご飯にかけてチーズを乗せる。'],
        cookTime: '約10分', tips: 'トルティーヤチップスを砕いて添えても美味しい。'
    },
    {
        id: 'retort-pasta-mentaiko',
        name: 'レトルト明太子パスタ',
        meal: 'lunch', servings: 1, difficulty: 'easy', season: ['spring', 'summer', 'autumn', 'winter'],
        calories: '約500kcal', activeTime: '10分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: 'レトルトの明太子ソースで作るクリーミーパスタ。',
        ingredients: ['パスタ', 'レトルト明太子パスタソース', '刻み海苔', '大葉'],
        requiredGear: ['鍋'], usedGearIds: ['titanium-pot'], usedHeatSourceIds: ['single-burner'],
        steps: ['パスタを茹でる。', 'ソースを和えて海苔と大葉を乗せる。'],
        cookTime: '約10分', tips: '生クリームを少し足すとさらに濃厚。'
    },
    {
        id: 'frozen-edamame-snack',
        name: '冷凍枝豆',
        meal: 'snack', servings: 2, difficulty: 'easy', season: ['summer'],
        calories: '約150kcal', activeTime: '5分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: '冷凍枝豆を熱湯で戻すだけ。キャンプでも定番おつまみ。',
        ingredients: ['冷凍枝豆', '塩'],
        requiredGear: ['鍋'], usedGearIds: ['titanium-pot'], usedHeatSourceIds: ['single-burner'],
        steps: ['お湯を沸かして枝豆を入れる。', '2〜3分茹でて塩を振る。'],
        cookTime: '約5分', tips: 'ニンニクと唐辛子で炒めるとペペロンチーノ風に。'
    },
    {
        id: 'retort-pasta-napolitan',
        name: 'レトルトナポリタン',
        meal: 'lunch', servings: 1, difficulty: 'easy', season: ['spring', 'summer', 'autumn', 'winter'],
        calories: '約500kcal', activeTime: '10分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: 'レトルトソースで作る懐かしの味。',
        ingredients: ['パスタ', 'レトルトナポリタンソース', '粉チーズ', 'タバスコ'],
        requiredGear: ['鍋'], usedGearIds: ['titanium-pot'], usedHeatSourceIds: ['single-burner'],
        steps: ['パスタを茹でる。', 'ソースを和える。', 'チーズとタバスコをたっぷり。'],
        cookTime: '約10分', tips: 'ウインナーを焼いて添えると豪華に。'
    }
];
