
export const noodleRecipes = [
    // Existing
    {
        id: 'yakisoba',
        name: '鉄板焼きそば',
        meal: 'lunch', servings: 4, difficulty: 'easy', season: ['summer'],
        calories: '約500kcal', activeTime: '15分', cleanupLevel: 2, prePrep: true, cost: 'low',
        description: 'キャンプランチの絶対王者。外で食べると何倍も美味しい。',
        ingredients: ['焼きそば麺 (4玉)', '豚バラ肉', 'キャベツ', 'もやし', '人参', '付属の粉ソース'],
        requiredGear: ['鉄板またはマルチグリドル'], usedGearIds: ['iron-plate', 'griddle'], usedHeatSourceIds: ['twin-burner', 'bonfire'],
        steps: ['肉と野菜を炒める。', '麺を入れ、水を少し加えて蒸し焼きにしてほぐす。', 'ソースを加えて水分を飛ばしながら炒め合わせる。'],
        cookTime: '約15分', tips: '最後に目玉焼きを乗せると豪華になります。'
    },
    {
        id: 'meat-sauce-pasta',
        name: 'ゴロゴロお肉のミートソース',
        meal: 'lunch', servings: 2, difficulty: 'normal', season: ['spring', 'autumn'],
        calories: '約600kcal', activeTime: '20分', cleanupLevel: 2, prePrep: true, cost: 'low',
        description: '手作りミートソースは格別の味。一度作れば冷凍して持っていける。',
        ingredients: ['パスタ', '合い挽き肉', '玉ねぎ', 'トマト缶', 'ケチャップ', 'ソース'],
        requiredGear: ['鍋', 'フライパン'], usedGearIds: ['titanium-pot', 'skillet'], usedHeatSourceIds: ['twin-burner'],
        steps: ['ソースを作る（玉ねぎ、肉炒め、トマト缶と調味料で煮込む）。', 'パスタを茹でてソースをかける。'],
        cookTime: '約20分（ソース持参なら10分）', tips: 'フェットチーネなど太めの麺が合います。'
    },
    {
        id: 'camp-ramen',
        name: '朝ラーメン（朝ラー）',
        meal: 'breakfast', servings: 1, difficulty: 'easy', season: ['autumn', 'winter'],
        calories: '約450kcal', activeTime: '5分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: '寒い朝、冷えた体に染み渡る至福の一杯。',
        ingredients: ['インスタントラーメン（袋麺）', '卵', '刻みネギ', '焼き豚（市販）'],
        requiredGear: ['クッカー（小）'], usedGearIds: ['titanium-pot', 'mestin'], usedHeatSourceIds: ['single-burner'],
        steps: ['お湯を沸かし、麺を茹でる。', '卵を落として少し煮る。', 'スープを溶かし、具を乗せる。'],
        cookTime: '約5分', tips: 'カット野菜を入れると罪悪感が薄れます。'
    },
    {
        id: 'penne-gratin',
        name: 'ペンネグラタン',
        meal: 'dinner', servings: 2, difficulty: 'normal', season: ['winter'],
        calories: '約600kcal', activeTime: '20分', cleanupLevel: 2, prePrep: true, cost: 'mid',
        description: 'ダッチオーブンやスキレットで焼く熱々のグラタン。',
        ingredients: ['ペンネ', 'ホワイトソース缶', '鶏肉', 'ブロッコリー', 'チーズ', 'パン粉'],
        requiredGear: ['スキレット'], usedGearIds: ['skillet'], usedHeatSourceIds: ['wood-stove', 'bonfire'],
        steps: ['ペンネを茹でる（または早ゆでタイプ）。', '具材を炒め、ホワイトソースとペンネを和える。', 'チーズとパン粉を乗せ、蓋をして上火で焦げ目がつくまで焼く。'],
        cookTime: '約30分', tips: 'マカロニでもOK。'
    },
    {
        id: 'udon-suki',
        name: '具だくさんうどんすき',
        meal: 'dinner', servings: 4, difficulty: 'easy', season: ['winter'],
        calories: '約400kcal', activeTime: '15分', cleanupLevel: 2, prePrep: true, cost: 'mid',
        description: 'いろいろな具材から出る出汁を吸ったうどんが最高。',
        ingredients: ['うどん玉', '鶏肉', '白菜', '椎茸', 'カマボコ', '油揚げ', 'うどんスープ'],
        requiredGear: ['土鍋またはダッチオーブン'], usedGearIds: ['bottom-wide-cooker'], usedHeatSourceIds: ['cassette-stove'],
        steps: ['つゆを沸かし、具材を煮る。', '最後にうどんを入れて温める。'],
        cookTime: '約20分', tips: '冷凍うどんがコシがあっておすすめです。'
    },
    {
        id: 'cold-somen',
        name: '流水素麺',
        meal: 'lunch', servings: 2, difficulty: 'easy', season: ['summer'],
        calories: '約300kcal', activeTime: '10分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: '暑い夏にさっぱりと。川の水（※要確認）で冷やすのも乙。',
        ingredients: ['素麺', 'めんつゆ', '薬味（ネギ、生姜、ミョウガ）', '氷'],
        requiredGear: ['鍋', 'ザル', 'ボウル'], usedGearIds: ['titanium-pot'], usedHeatSourceIds: ['single-burner'],
        steps: ['素麺を規定時間茹でる。', '水でしっかりとぬめりを取りながら冷やす。', '氷水に浮かべて食べる。'],
        cookTime: '約10分', tips: '缶詰のミカンやサクランボを入れると昭和感が出ます。'
    },
    {
        id: 'yakisoba-salt',
        name: '海鮮塩焼きそば',
        meal: 'lunch', servings: 2, difficulty: 'easy', season: ['summer'],
        calories: '約450kcal', activeTime: '15分', cleanupLevel: 2, prePrep: false, cost: 'mid',
        description: 'ソースとは違ったあっさり味。レモンを絞って。',
        ingredients: ['焼きそば麺', 'シーフードミックス', 'ニラ', 'もやし', '鶏ガラスープの素', '塩ダレ'],
        requiredGear: ['鉄板'], usedGearIds: ['iron-plate'], usedHeatSourceIds: ['twin-burner'],
        steps: ['シーフードと野菜を炒める。', '麺を入れ、酒少々でほぐす。', '塩ダレで調味する。'],
        cookTime: '約15分', tips: '黒胡椒を多めに振ると味が締まります。'
    },
    {
        id: 'carbonara',
        name: '失敗しないワンパンカルボナーラ',
        meal: 'lunch', servings: 2, difficulty: 'normal', season: ['spring', 'autumn', 'winter'],
        calories: '約700kcal', activeTime: '15分', cleanupLevel: 2, prePrep: false, cost: 'low',
        description: 'ダマになりにくいレシピ。濃厚なソースがたまらない。',
        ingredients: ['パスタ', 'ベーコン', '卵', '粉チーズ', '牛乳', 'コンソメ'],
        requiredGear: ['フライパン'], usedGearIds: ['skillet'], usedHeatSourceIds: ['single-burner'],
        steps: ['少なめの水でパスタを茹で、水分を飛ばす。', '火を止めてから、混ぜておいた卵液（卵・チーズ・牛乳）を入れて予熱で和える。'],
        cookTime: '約15分', tips: '火にかけたまま卵液を入れるとスクランブルエッグになるので注意。'
    },
    {
        id: 'curry-udon',
        name: '昨日のカレーでカレーうどん',
        meal: 'breakfast', servings: 2, difficulty: 'easy', season: ['spring', 'autumn', 'winter'],
        calories: '約500kcal', activeTime: '10分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: 'キャンプ2日目の定番リメイク料理。',
        ingredients: ['残ったカレー', 'うどん玉', 'だし醤油（またはめんつゆ）', 'ネギ'],
        requiredGear: ['鍋'], usedGearIds: ['titanium-pot'], usedHeatSourceIds: ['single-burner'],
        steps: ['残ったカレーに水とめんつゆを加えて伸ばす。', 'うどんを入れて煮込む。'],
        cookTime: '約10分', tips: '餅を入れると力うどんになります。'
    },
    {
        id: 'pepperoncino',
        name: 'キャベツとアンチョビのペペロンチーノ',
        meal: 'lunch', servings: 2, difficulty: 'normal', season: ['spring', 'summer'],
        calories: '約500kcal', activeTime: '15分', cleanupLevel: 1, prePrep: false, cost: 'mid',
        description: 'シンプルながら奥深い味。白ワインに合う。',
        ingredients: ['パスタ', 'キャベツ', 'アンチョビフィレ', 'ニンニク', '鷹の爪', 'オリーブオイル'],
        requiredGear: ['フライパン', '鍋'], usedGearIds: ['skillet'], usedHeatSourceIds: ['single-burner'],
        steps: ['パスタを茹でる。', 'フライパンでニンニク、鷹の爪、アンチョビを炒め、キャベツを加える。', 'あがり際にパスタと茹で汁を加えて乳化させる。'],
        cookTime: '約15分', tips: 'アンチョビの塩気が強いので塩は控えめに。'
    },
    // New Additions
    {
        id: 'napolitan',
        name: '喫茶店のナポリタン',
        meal: 'lunch', servings: 2, difficulty: 'easy', season: ['spring', 'summer', 'autumn', 'winter'],
        calories: '約600kcal', activeTime: '15分', cleanupLevel: 2, prePrep: false, cost: 'low',
        description: 'ケチャップをしっかり炒めるのがコツ。ピーマンの苦味がアクセント。',
        ingredients: ['太めのパスタ', 'ウインナー', '玉ねぎ', 'ピーマン', 'ケチャップ', '牛乳'],
        requiredGear: ['フライパン'], usedGearIds: ['skillet'], usedHeatSourceIds: ['single-burner'],
        steps: ['具材を炒める。', 'ケチャップを入れて煮詰め、酸味を飛ばす。', '茹でたパスタと牛乳少々を加えて混ぜる。'],
        cookTime: '約20分', tips: 'タバスコと粉チーズをたっぷりと。'
    },
    {
        id: 'houtou',
        name: 'かぼちゃたっぷりの山梨ほうとう',
        meal: 'dinner', servings: 4, difficulty: 'normal', season: ['winter'],
        calories: '約500kcal', activeTime: '30分', cleanupLevel: 2, prePrep: true, cost: 'low',
        description: '麺にとろみがついて体が温まる。冬キャンプの定番。',
        ingredients: ['ほうとう麺（またはきしめん）', 'かぼちゃ', '豚肉', '油揚げ', '味噌'],
        requiredGear: ['鍋'], usedGearIds: ['bottom-wide-cooker'], usedHeatSourceIds: ['wood-stove'],
        steps: ['かぼちゃが溶けるくらいまで具材を煮込む。', '麺を入れてさらに煮込む。'],
        cookTime: '約30分', tips: '翌朝、ドロドロになったスープにご飯を入れると飛びます。'
    },
    {
        id: 'cold-pasta',
        name: 'トマトとバジルの冷製パスタ',
        meal: 'lunch', servings: 2, difficulty: 'easy', season: ['summer'],
        calories: '約400kcal', activeTime: '15分', cleanupLevel: 2, prePrep: false, cost: 'mid',
        description: 'カッペリーニなどの細麺で。氷水で締めるのが重要。',
        ingredients: ['細いパスタ', 'トマト', 'モッツァレラチーズ', 'バジル', 'オリーブオイル', 'レモン汁'],
        requiredGear: ['鍋', 'ボウル', 'ザル'], usedGearIds: ['titanium-pot'], usedHeatSourceIds: ['single-burner'],
        steps: ['パスタを表示より長く茹で、氷水で急冷する。', 'ボウルで具材とソースを乳化させ、パスタを絡める。'],
        cookTime: '約15分', tips: 'ソースも冷やしておくとより美味しいです。'
    },
    {
        id: 'yaki-udon',
        name: '醤油香る焼きうどん',
        meal: 'lunch', servings: 2, difficulty: 'easy', season: ['spring', 'summer', 'autumn'],
        calories: '約500kcal', activeTime: '10分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: '鰹節が踊る。お手軽ランチ。',
        ingredients: ['うどん玉', '豚肉', 'キャベツ', '醤油', '鰹節'],
        requiredGear: ['鉄板', 'フライパン'], usedGearIds: ['iron-plate', 'skillet'], usedHeatSourceIds: ['twin-burner'],
        steps: ['具材を炒め、うどんを入れる。', '鍋肌から醤油を回し入れる。'],
        cookTime: '約10分', tips: '冷凍うどんを使うとコシが出ます。'
    },
    {
        id: 'soup-pasta',
        name: 'スープパスタ',
        meal: 'breakfast', servings: 1, difficulty: 'easy', season: ['spring', 'autumn'],
        calories: '約400kcal', activeTime: '10分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: 'お湯を沸かして素を入れるだけ。',
        ingredients: ['スープパスタの素（カップ）', 'お湯'],
        requiredGear: ['シェラカップ'], usedGearIds: ['sierra-cup'], usedHeatSourceIds: ['single-burner'],
        steps: ['お湯を注ぐ。'],
        cookTime: '3分', tips: '朝はこれくらいでいいんです。'
    },
    {
        id: 'okinawa-soba',
        name: '沖縄そば',
        meal: 'lunch', servings: 2, difficulty: 'easy', season: ['summer'],
        calories: '約500kcal', activeTime: '15分', cleanupLevel: 1, prePrep: false, cost: 'mid',
        description: 'ラフテー（角煮）を乗せて。コーレーグースを忘れずに。',
        ingredients: ['沖縄そば麺', 'そばだし', 'ラフテー（レトルト）', '紅生姜', 'ネギ'],
        requiredGear: ['鍋'], usedGearIds: ['titanium-pot'], usedHeatSourceIds: ['single-burner'],
        steps: ['麺を湯通しする。', '温めたつゆをかけ、具を乗せる。'],
        cookTime: '約10分', tips: 'スパムを乗せても美味しいです。'
    },
    {
        id: 'short-pasta-salad',
        name: 'フジッリのパスタサラダ',
        meal: 'lunch', servings: 4, difficulty: 'easy', season: ['spring', 'summer'],
        calories: '約300kcal', activeTime: '15分', cleanupLevel: 2, prePrep: true, cost: 'low',
        description: '作り置きできるので初日のランチに最適。',
        ingredients: ['フジッリ（ねじりパスタ）', 'ハム', 'きゅうり', 'コーン', 'マヨネーズ', '塩コショウ'],
        requiredGear: ['鍋'], usedGearIds: ['titanium-pot'], usedHeatSourceIds: ['single-burner'],
        steps: ['パスタを茹でて冷水で冷やす。', '具材とマヨネーズで和える。'],
        cookTime: '約15分', tips: '隠し味に砂糖を少し入れるとデパ地下の味になります。'
    },
    {
        id: 'tantan-men',
        name: '豆乳担々麺',
        meal: 'lunch', servings: 1, difficulty: 'normal', season: ['winter'],
        calories: '約600kcal', activeTime: '15分', cleanupLevel: 2, prePrep: true, cost: 'mid',
        description: '豆乳でまろやかに仕上げたピリ辛麺。',
        ingredients: ['中華麺', '豆乳', '鶏ガラスープ', '肉味噌', 'ラー油', 'チンゲン菜'],
        requiredGear: ['鍋'], usedGearIds: ['titanium-pot'], usedHeatSourceIds: ['single-burner'],
        steps: ['スープを沸かし豆乳を入れる（沸騰させない）。', '茹でた麺にかけ、肉味噌を乗せる。'],
        cookTime: '約15分', tips: 'すりごまをたっぷり入れるとコクが出ます。'
    },
    {
        id: 'ankake-yakisoba',
        name: '五目あんかけ焼きそば',
        meal: 'lunch', servings: 2, difficulty: 'normal', season: ['spring', 'autumn'],
        calories: '約600kcal', activeTime: '20分', cleanupLevel: 2, prePrep: true, cost: 'low',
        description: '麺をカリカリに焼くのがポイント。',
        ingredients: ['焼きそば麺', '豚肉', '白菜', '海老', 'うずらの卵', 'とろみの素（中華丼の素）'],
        requiredGear: ['フライパン'], usedGearIds: ['skillet'], usedHeatSourceIds: ['single-burner'],
        steps: ['多めの油で麺を揚げ焼きにする。', 'レトルトの中華丼の素を温めてかける（手抜き）。'],
        cookTime: '約15分', tips: 'お酢と辛子を添えて。'
    },
    {
        id: 'nyumen',
        name: '温かいにゅうめん',
        meal: 'breakfast', servings: 1, difficulty: 'easy', season: ['spring', 'autumn'],
        calories: '約300kcal', activeTime: '5分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: '余った素麺で作る温かい汁物。',
        ingredients: ['素麺', 'めんつゆ', '卵', 'ネギ'],
        requiredGear: ['クッカー'], usedGearIds: ['titanium-pot'], usedHeatSourceIds: ['single-burner'],
        steps: ['つゆで素麺をそのまま煮る（塩分注意）。'],
        cookTime: '5分', tips: 'とろみがついて温まります。'
    },
    {
        id: 'tai-noodle',
        name: 'パッタイ（タイ風焼きそば）',
        meal: 'lunch', servings: 2, difficulty: 'hard', season: ['summer'],
        calories: '約500kcal', activeTime: '20分', cleanupLevel: 2, prePrep: true, cost: 'mid',
        description: '甘酸っぱいタマリンドソースが癖になる。',
        ingredients: ['米麺（センレック）', 'エビ', '厚揚げ', 'もやし', 'ニラ', 'ピーナッツ', 'パッタイペースト'],
        requiredGear: ['フライパン'], usedGearIds: ['skillet'], usedHeatSourceIds: ['single-burner'],
        steps: ['麺をぬるま湯で戻しておく。', '具材を炒め、麺とソースを入れて絡める。', '卵を割り入れ炒め合わせる。'],
        cookTime: '約20分', tips: 'レモンと砂糖、唐辛子で味変を楽しんで。'
    },
    {
        id: 'curry-ramen',
        name: '室蘭カレーラーメン風',
        meal: 'lunch', servings: 1, difficulty: 'easy', season: ['winter'],
        calories: '約600kcal', activeTime: '10分', cleanupLevel: 2, prePrep: false, cost: 'low',
        description: 'カレースープとちぢれ麺の相性。',
        ingredients: ['生ラーメン（味噌）', 'カレー粉', 'チャーシュー', 'わかめ'],
        requiredGear: ['鍋'], usedGearIds: ['titanium-pot'], usedHeatSourceIds: ['single-burner'],
        steps: ['味噌ラーメンを作り、カレー粉をドバッと入れる。'],
        cookTime: '約10分', tips: 'とろけるチーズトッピングが合います。'
    },
    {
        id: 'genovese',
        name: 'ジャガイモとインゲンのジェノベーゼ',
        meal: 'lunch', servings: 2, difficulty: 'normal', season: ['spring', 'summer'],
        calories: '約600kcal', activeTime: '20分', cleanupLevel: 2, prePrep: false, cost: 'high',
        description: 'バジルソースの鮮やかな緑。',
        ingredients: ['パスタ', 'ジェノベーゼソース（瓶）', 'ジャガイモ', 'インゲン'],
        requiredGear: ['鍋'], usedGearIds: ['titanium-pot'], usedHeatSourceIds: ['single-burner'],
        steps: ['パスタと一緒に野菜も茹でる。', '湯切りしてソースを和える。'],
        cookTime: '約20分', tips: '茹で汁を少し残すと混ざりやすいです。'
    },
    {
        id: 'mac-n-cheese',
        name: 'マカロニ＆チーズ',
        meal: 'snack', servings: 2, difficulty: 'easy', season: ['spring', 'summer', 'autumn', 'winter'],
        calories: '約500kcal', activeTime: '15分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: 'アメリカの国民食。ジャンクだけどやめられない。',
        ingredients: ['マカロニ', 'チェダーチーズ', '牛乳', 'バター'],
        requiredGear: ['スキレット'], usedGearIds: ['skillet'], usedHeatSourceIds: ['single-burner'],
        steps: ['マカロニを茹でる。', '湯を捨て、チーズ、牛乳、バターを入れて混ぜる。'],
        cookTime: '約15分', tips: '箱入りの「KRAFT」を持っていけば最高に簡単。'
    },
    {
        id: 'dish-sara-udon',
        name: 'あんかけ皿うどん',
        meal: 'lunch', servings: 2, difficulty: 'easy', season: ['spring', 'autumn'],
        calories: '約500kcal', activeTime: '10分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: '揚げ麺にかけるだけ。湿気った麺も復活。',
        ingredients: ['皿うどん（揚げ麺）', '中華丼の具（レトルト）', 'お酢'],
        requiredGear: ['シェラカップ', '鍋（湯煎用）'], usedGearIds: ['sierra-cup', 'titanium-pot'], usedHeatSourceIds: ['single-burner'],
        steps: ['レトルトを温めて麺にかける。'],
        cookTime: '5分', tips: '金蝶ソースを持参する通もいます。'
    },
    // ===== ピザ・パスタ追加レシピ（10件）=====
    {
        id: 'skillet-pizza-margherita',
        name: 'スキレットピザ・マルゲリータ',
        meal: 'dinner', servings: 2, difficulty: 'normal', season: ['spring', 'summer', 'autumn', 'winter'],
        calories: '約600kcal', activeTime: '25分', cleanupLevel: 2, prePrep: true, cost: 'mid',
        description: '生地から作る本格ピザ。スキレットで石窯風の焼き上がり。',
        ingredients: ['ピザ生地（市販または冷凍）', 'トマトソース', 'モッツァレラチーズ', 'バジル', 'オリーブオイル'],
        requiredGear: ['スキレット'], usedGearIds: ['skillet'], usedHeatSourceIds: ['single-burner', 'bonfire'],
        steps: ['スキレットにオイルを塗り生地を敷く。', 'ソースとチーズを乗せる。', '蓋をして焼き、バジルを乗せる。'],
        cookTime: '約15分', tips: '蓋に炭を乗せると上火も効いてプロ級に。'
    },
    {
        id: 'tortilla-pizza',
        name: 'トルティーヤピザ',
        meal: 'snack', servings: 2, difficulty: 'easy', season: ['spring', 'summer', 'autumn', 'winter'],
        calories: '約400kcal', activeTime: '10分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: 'トルティーヤで作る薄焼きピザ。生地を作る手間なし。',
        ingredients: ['トルティーヤ', 'ピザソース（またはケチャップ）', 'チーズ', 'サラミ', 'ピーマン'],
        requiredGear: ['スキレット'], usedGearIds: ['skillet'], usedHeatSourceIds: ['single-burner'],
        steps: ['スキレットにトルティーヤを乗せる。', 'ソースと具材を乗せて蓋をして焼く。'],
        cookTime: '約5分', tips: 'パリパリ生地がクリスピーピザ風。'
    },
    {
        id: 'naan-pizza',
        name: 'ナンピザ',
        meal: 'lunch', servings: 2, difficulty: 'easy', season: ['spring', 'summer', 'autumn', 'winter'],
        calories: '約450kcal', activeTime: '10分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: '市販のナンを使った簡単ピザ。もちもち食感。',
        ingredients: ['市販のナン', 'トマトソース', 'チーズ', 'ベーコン', 'オリーブ'],
        requiredGear: ['スキレット', '鉄板'], usedGearIds: ['skillet', 'iron-plate'], usedHeatSourceIds: ['single-burner'],
        steps: ['ナンに具材を乗せる。', 'スキレットで焼いてチーズを溶かす。'],
        cookTime: '約10分', tips: 'カレー粉を振るとインド風に。'
    },
    {
        id: 'pasta-vongole',
        name: 'あさりのボンゴレビアンコ',
        meal: 'dinner', servings: 2, difficulty: 'normal', season: ['spring', 'summer'],
        calories: '約500kcal', activeTime: '20分', cleanupLevel: 2, prePrep: false, cost: 'mid',
        description: 'あさりの旨味が染み出たシンプルパスタ。白ワインと。',
        ingredients: ['パスタ', 'あさり（殻付きまたは缶詰）', 'にんにく', '白ワイン', 'オリーブオイル', 'パセリ'],
        requiredGear: ['鍋', 'フライパン'], usedGearIds: ['titanium-pot', 'skillet'], usedHeatSourceIds: ['twin-burner'],
        steps: ['にんにくを炒め、あさりと白ワインを加えて蓋をする。', '殻が開いたらパスタと茹で汁を加えて乳化させる。'],
        cookTime: '約20分', tips: '缶詰のあさりなら超簡単。汁も使って。'
    },
    {
        id: 'pasta-bacon-mushroom',
        name: 'ベーコンときのこのパスタ',
        meal: 'lunch', servings: 2, difficulty: 'easy', season: ['autumn', 'winter'],
        calories: '約550kcal', activeTime: '15分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: 'バター醤油の香りが食欲をそそる和風パスタ。',
        ingredients: ['パスタ', 'ベーコン', 'しめじ', 'バター', '醤油', '刻み海苔'],
        requiredGear: ['鍋', 'フライパン'], usedGearIds: ['titanium-pot', 'skillet'], usedHeatSourceIds: ['twin-burner'],
        steps: ['パスタを茹でる。', 'ベーコンときのこをバターで炒める。', 'パスタを加えて醤油で味付け。'],
        cookTime: '約15分', tips: 'にんにくを少し入れるとさらに香ばしい。'
    },
    {
        id: 'dutch-oven-pizza',
        name: 'ダッチオーブンピザ',
        meal: 'dinner', servings: 4, difficulty: 'hard', season: ['autumn', 'winter'],
        calories: '約650kcal', activeTime: '30分', cleanupLevel: 3, prePrep: true, cost: 'mid',
        description: '焚き火でじっくり焼く本格ピザ。外はカリッと中はふんわり。',
        ingredients: ['ピザ生地', 'トマトソース', 'モッツァレラチーズ', 'サラミ', 'ピーマン', 'オリーブ'],
        requiredGear: ['ダッチオーブン'], usedGearIds: ['bottom-wide-cooker'], usedHeatSourceIds: ['bonfire', 'wood-stove'],
        steps: ['ダッチオーブンを予熱する。', 'クッキングシートを敷いて生地と具材を入れる。', '蓋に炭を乗せて上下から焼く。'],
        cookTime: '約25分', tips: '底が焦げやすいので注意。石を敷くとよい。'
    },
    {
        id: 'pasta-tuna-mayo',
        name: 'ツナマヨパスタ',
        meal: 'lunch', servings: 1, difficulty: 'easy', season: ['spring', 'summer', 'autumn', 'winter'],
        calories: '約500kcal', activeTime: '10分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: '子供も大好きなマヨネーズ味のパスタ。',
        ingredients: ['パスタ', 'ツナ缶', 'マヨネーズ', '醤油', '刻み海苔', '大葉'],
        requiredGear: ['鍋'], usedGearIds: ['titanium-pot'], usedHeatSourceIds: ['single-burner'],
        steps: ['パスタを茹でる。', 'ツナとマヨネーズ、醤油で和える。', 'トッピングを乗せる。'],
        cookTime: '約10分', tips: '温かいままでも冷やしても美味しい。'
    },
    {
        id: 'gyoza-skin-pizza',
        name: '餃子の皮ミニピザ',
        meal: 'snack', servings: 2, difficulty: 'easy', season: ['spring', 'summer', 'autumn', 'winter'],
        calories: '約250kcal', activeTime: '15分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: '餃子の皮で作る一口サイズのミニピザ。おつまみに最高。',
        ingredients: ['餃子の皮', 'ケチャップ', 'チーズ', 'ベーコン', 'コーン'],
        requiredGear: ['スキレット'], usedGearIds: ['skillet'], usedHeatSourceIds: ['single-burner'],
        steps: ['スキレットに餃子の皮を並べる。', '具材を乗せて蓋をして焼く。'],
        cookTime: '約10分', tips: 'パリパリに焼くとスナック感覚。'
    },
    {
        id: 'pasta-anchovy-cabbage',
        name: 'キャベツとアンチョビのパスタ',
        meal: 'lunch', servings: 2, difficulty: 'normal', season: ['spring', 'summer'],
        calories: '約500kcal', activeTime: '15分', cleanupLevel: 1, prePrep: false, cost: 'mid',
        description: 'アンチョビの塩気とキャベツの甘みが絶妙。',
        ingredients: ['パスタ', 'キャベツ', 'アンチョビ', 'にんにく', '唐辛子', 'オリーブオイル'],
        requiredGear: ['鍋', 'フライパン'], usedGearIds: ['titanium-pot', 'skillet'], usedHeatSourceIds: ['twin-burner'],
        steps: ['パスタとキャベツを一緒に茹でる。', 'にんにくとアンチョビを炒め、パスタを加える。'],
        cookTime: '約15分', tips: 'アンチョビの塩気があるので塩は控えめに。'
    },
    {
        id: 'pasta-mentaiko-cream',
        name: '明太子クリームパスタ',
        meal: 'lunch', servings: 2, difficulty: 'easy', season: ['spring', 'summer', 'autumn', 'winter'],
        calories: '約600kcal', activeTime: '15分', cleanupLevel: 1, prePrep: false, cost: 'mid',
        description: 'ピリ辛クリーミーな人気パスタ。',
        ingredients: ['パスタ', '明太子', '生クリーム', 'バター', '刻み海苔', '大葉'],
        requiredGear: ['鍋', 'フライパン'], usedGearIds: ['titanium-pot', 'skillet'], usedHeatSourceIds: ['twin-burner'],
        steps: ['パスタを茹でる。', '火を止めてから明太子、生クリーム、バターを和える。'],
        cookTime: '約15分', tips: '明太子は火を通しすぎないのがコツ。'
    },
    // ===== ワンポットパスタ（10件）=====
    {
        id: 'one-pot-cream-pasta',
        name: 'ワンポット・クリームパスタ',
        meal: 'lunch', servings: 2, difficulty: 'easy', season: ['autumn', 'winter'],
        calories: '約650kcal', activeTime: '15分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: '牛乳で直接パスタを煮込む濃厚ワンポット。',
        ingredients: ['パスタ（早茹で）', '牛乳', '水', 'コンソメ', 'ベーコン', 'きのこ', '粉チーズ'],
        requiredGear: ['深型鍋'], usedGearIds: ['titanium-pot'], usedHeatSourceIds: ['single-burner'],
        steps: ['水と牛乳、コンソメを沸かす。', 'パスタと具材を入れて表示時間煮込む。', '粉チーズを加えて混ぜる。'],
        cookTime: '約15分', tips: '牛乳は沸騰させすぎると分離するので弱火で。'
    },
    {
        id: 'one-pot-tuna-tomato',
        name: 'ワンポット・ツナトマトパスタ',
        meal: 'lunch', servings: 2, difficulty: 'easy', season: ['spring', 'summer'],
        calories: '約500kcal', activeTime: '15分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: '缶詰だけで完結するキャンプの味方。',
        ingredients: ['パスタ', 'トマト缶', 'ツナ缶', '水', 'コンソメ', 'にんにく', 'オリーブオイル'],
        requiredGear: ['深型鍋'], usedGearIds: ['titanium-pot'], usedHeatSourceIds: ['single-burner'],
        steps: ['全材料を鍋に入れて火にかける。', 'パスタが柔らかくなるまで煮込む。'],
        cookTime: '約15分', tips: 'バジルを散らすと見た目アップ。'
    },
    {
        id: 'one-pot-meat-sauce',
        name: 'ワンポット・ミートソースパスタ',
        meal: 'dinner', servings: 2, difficulty: 'easy', season: ['spring', 'summer', 'autumn', 'winter'],
        calories: '約650kcal', activeTime: '20分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: 'ひき肉から作るワンポットミートソース。',
        ingredients: ['パスタ', '合い挽き肉', 'トマト缶', '玉ねぎ', '水', 'コンソメ', 'ケチャップ'],
        requiredGear: ['深型鍋'], usedGearIds: ['titanium-pot'], usedHeatSourceIds: ['single-burner'],
        steps: ['肉と玉ねぎを炒める。', 'トマト缶、水、コンソメを加えて煮立てる。', 'パスタを折って入れ、煮込む。'],
        cookTime: '約20分', tips: '時々かき混ぜてくっつき防止。'
    },
    {
        id: 'one-pot-peperoncino',
        name: 'ワンポット・ペペロンチーノ',
        meal: 'lunch', servings: 1, difficulty: 'easy', season: ['spring', 'summer', 'autumn', 'winter'],
        calories: '約450kcal', activeTime: '10分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: 'にんにくと唐辛子の香りが食欲をそそる。',
        ingredients: ['パスタ', 'にんにく', '唐辛子', 'オリーブオイル', '水', '塩', 'パセリ'],
        requiredGear: ['深型鍋'], usedGearIds: ['titanium-pot'], usedHeatSourceIds: ['single-burner'],
        steps: ['にんにくと唐辛子を油で炒める。', '水を加えてパスタを煮込む。', '水分が飛んだら完成。'],
        cookTime: '約12分', tips: 'ベーコンを加えるとボリュームアップ。'
    },
    {
        id: 'one-pot-bacon-spinach',
        name: 'ワンポット・ベーコンとほうれん草のパスタ',
        meal: 'lunch', servings: 2, difficulty: 'easy', season: ['autumn', 'winter'],
        calories: '約550kcal', activeTime: '15分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: 'クリームなしでもコクがあるバター醤油味。',
        ingredients: ['パスタ', 'ベーコン', 'ほうれん草（冷凍可）', 'バター', '醤油', '水', 'コンソメ'],
        requiredGear: ['深型鍋'], usedGearIds: ['titanium-pot'], usedHeatSourceIds: ['single-burner'],
        steps: ['ベーコンを炒め、水とコンソメを加える。', 'パスタを煮込み、最後にほうれん草とバター醤油で仕上げる。'],
        cookTime: '約15分', tips: '冷凍ほうれん草なら解凍不要で便利。'
    },
    {
        id: 'one-pot-shrimp-cream',
        name: 'ワンポット・海老クリームパスタ',
        meal: 'dinner', servings: 2, difficulty: 'easy', season: ['autumn', 'winter'],
        calories: '約600kcal', activeTime: '15分', cleanupLevel: 1, prePrep: false, cost: 'mid',
        description: '冷凍海老で作るご馳走パスタ。',
        ingredients: ['パスタ', '冷凍海老', '牛乳', '水', 'コンソメ', 'バター', '塩コショウ'],
        requiredGear: ['深型鍋'], usedGearIds: ['titanium-pot'], usedHeatSourceIds: ['single-burner'],
        steps: ['牛乳と水を沸かし、パスタと海老を煮込む。', 'バターを加えてとろみが出たら完成。'],
        cookTime: '約15分', tips: 'アスパラやブロッコリーを加えても美味しい。'
    },
    {
        id: 'one-pot-puttanesca',
        name: 'ワンポット・プッタネスカ',
        meal: 'lunch', servings: 2, difficulty: 'easy', season: ['spring', 'summer'],
        calories: '約500kcal', activeTime: '15分', cleanupLevel: 1, prePrep: false, cost: 'mid',
        description: 'オリーブとケッパーのパンチが効いた大人の味。',
        ingredients: ['パスタ', 'トマト缶', 'アンチョビ', 'オリーブ', 'ケッパー', 'にんにく', '水'],
        requiredGear: ['深型鍋'], usedGearIds: ['titanium-pot'], usedHeatSourceIds: ['single-burner'],
        steps: ['にんにくとアンチョビを炒める。', 'トマト缶と水、パスタを加えて煮込む。', 'オリーブとケッパーを加えて完成。'],
        cookTime: '約15分', tips: '唐辛子を加えると辛さアップ。'
    },
    {
        id: 'one-pot-corn-butter',
        name: 'ワンポット・コーンバターパスタ',
        meal: 'lunch', servings: 2, difficulty: 'easy', season: ['summer', 'autumn'],
        calories: '約550kcal', activeTime: '12分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: '子供も大好きな甘いコーンとバターの組み合わせ。',
        ingredients: ['パスタ', 'コーン缶', 'バター', '醤油', '水', 'コンソメ', 'パセリ'],
        requiredGear: ['深型鍋'], usedGearIds: ['titanium-pot'], usedHeatSourceIds: ['single-burner'],
        steps: ['水とコンソメを沸かし、パスタを煮込む。', 'コーンとバター、醤油を加えて仕上げる。'],
        cookTime: '約12分', tips: 'ブラックペッパーをたっぷりと。'
    },
    {
        id: 'one-pot-tomato-cheese',
        name: 'ワンポット・トマトチーズパスタ',
        meal: 'dinner', servings: 2, difficulty: 'easy', season: ['spring', 'summer', 'autumn', 'winter'],
        calories: '約600kcal', activeTime: '15分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: 'チーズがとろける簡単ワンポット。',
        ingredients: ['パスタ', 'トマト缶', 'ピザ用チーズ', '水', 'コンソメ', 'オリーブオイル', 'バジル'],
        requiredGear: ['深型鍋'], usedGearIds: ['titanium-pot'], usedHeatSourceIds: ['single-burner'],
        steps: ['水とトマト缶、コンソメでパスタを煮込む。', '最後にチーズを加えてとろけさせる。'],
        cookTime: '約15分', tips: 'チーズは火を止めてから加えるととろける。'
    },
    {
        id: 'one-pot-kimchi-pork',
        name: 'ワンポット・キムチ豚パスタ',
        meal: 'lunch', servings: 2, difficulty: 'easy', season: ['autumn', 'winter'],
        calories: '約600kcal', activeTime: '15分', cleanupLevel: 1, prePrep: false, cost: 'low',
        description: 'ピリ辛で食欲増進。韓国風ワンポット。',
        ingredients: ['パスタ', '豚バラ肉', 'キムチ', '水', '鶏ガラスープの素', 'ごま油', 'ネギ'],
        requiredGear: ['深型鍋'], usedGearIds: ['titanium-pot'], usedHeatSourceIds: ['single-burner'],
        steps: ['豚肉を炒める。', '水とスープの素、パスタを加えて煮込む。', '最後にキムチとごま油で仕上げる。'],
        cookTime: '約15分', tips: '卵黄をトッピングするとマイルドに。'
    }
];
